export { Canvas, type CanvasProps } from "./canvas.tsx"
export { Entity, Portal, Resource } from "./components.tsx"
export { $S3C } from "./constants.ts"
export { createEntity, createT } from "./create-t.tsx"
export { useFrame, useLoader, useThree } from "./hooks.ts"
export { useProps } from "./props.ts"
export * from "./raycasters.tsx"
export * as S3 from "./types.ts"
export { autodispose, getMeta, hasMeta, load, meta } from "./utils.ts"
