name: Publish to pkg.pr.new

on:
  push:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: install latest corepack
        run: npm install corepack@latest -g

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Publish preview
        run: pnpx pkg-pr-new publish --compact
